name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: echo  ${{ secrets.DATABASE_URL }}
      - run: npm install
      - run: npm run test:all
