name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
      - run: |
          touch .env
          echo DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres >> .env
          cat .env
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
      - run: npm install
      #   - run: npx prisma generate
      - run: npm run test:all
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
